title: Streamdata Gallery
url: tickets.streamdata.gallery
tag: Tickets
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: tickets
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
